version: 0.2

env:
  variables:
    S3_BUCKET: "yedamo-frontend-3si02day"
    CLOUDFRONT_ID: "E1LD293UU79DMN"
    SHOULD_BUILD: "true"

phases:
  pre_build:
    commands:
      - echo Logging in to AWS...
      - echo Build started on `date`
      - echo Checking for frontend changes...
      - |
        # Check if frontend directory has changes
        CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD 2>/dev/null || echo "frontend/")
        echo "Changed files: $CHANGED_FILES"
        
        if echo "$CHANGED_FILES" | grep -q "frontend/" || [ -z "$CHANGED_FILES" ]; then
          echo "Frontend changes detected or unable to determine changes. Proceeding with build..."
          echo "SHOULD_BUILD=true" >> $CODEBUILD_SRC_DIR/build_env
        else
          echo "No frontend changes detected. Skipping build..."
          echo "SHOULD_BUILD=false" >> $CODEBUILD_SRC_DIR/build_env
        fi
  
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - |
        source $CODEBUILD_SRC_DIR/build_env 2>/dev/null || true
        if [ "$SHOULD_BUILD" = "true" ]; then
          echo Installing dependencies...
          cd frontend
          npm install -g yarn@1.22.22
          yarn install --frozen-lockfile
        else
          echo Skipping install phase...
        fi
  
  build:
    commands:
      - |
        source $CODEBUILD_SRC_DIR/build_env 2>/dev/null || true
        if [ "$SHOULD_BUILD" = "true" ]; then
          echo Building the application...
          cd frontend
          yarn build
        else
          echo Skipping build phase...
        fi
      
  post_build:
    commands:
      - |
        source $CODEBUILD_SRC_DIR/build_env 2>/dev/null || true
        if [ "$SHOULD_BUILD" = "true" ]; then
          echo Build completed on `date`
          echo Uploading to S3...
          cd frontend
          aws s3 sync dist/ s3://$S3_BUCKET --delete --cache-control "max-age=31536000"
          aws s3 cp dist/index.html s3://$S3_BUCKET/index.html --cache-control "max-age=0, no-cache, no-store, must-revalidate"
          echo Invalidating CloudFront cache...
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"
          echo Frontend deployment completed successfully!
        else
          echo No deployment needed - no frontend changes detected
        fi

artifacts:
  files:
    - '**/*'
  base-directory: frontend/dist
  name: yedamo-frontend-$(date +%Y-%m-%d)